version: "2"
plugins:
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
exclude_patterns:
- "**/vendor/"
- "**.pb.go"
- "**_pb2.py"
- "**_pb.py"
- "**_test.go"
- "**mock/**.go"
- "mnemosynetest/**.go"
- "vendor/**/*"