version: "2"
plugins:
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
exclude_patterns:
  - "**.pb.go"
  - "**_pb2.py"
  - "**_pb.py"
  - "**_test.go"
  - "internal/storage/storagemock/"
  - "mnemosynetest/"
  - "mnemosynerpc/"
  - "scripts/"
  - "vendor/**/*"