version: "2"
plugins:
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
checks:
  method-complexity:
    config:
      threshold: 15
exclude_patterns:
  - "**/*_test.go"
  - "**/*_pb.py"
  - "**/*_pb2.py"
  - "**/*.pb.go"
  - "internal/storage/storagemock/"
  - "mnemosynetest/"
  - "mnemosynerpc/"
  - "scripts/"
  - "vendor/**/*"