language: go
addons:
  postgresql: "9.3"
go:
  - 1.4
  - tip
install:
  - go get .
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - go build
  - cp conf/travis_postgres.xml conf/testing.xml
  - ./mnemosyne init
  - cd test/lib && go get && go test -tags postgres
