language: go
addons:
  postgresql: '9.3'
env:
  MNEMOSYNE_LOGGER_FORMAT: humane
  MNEMOSYNE_LOGGER_ADAPTER: stdout
  MNEMOSYNE_LOGGER_LEVEL: 6
  MNEMOSYNE_STORAGE_POSTGRES_CONNECTION_STRING: postgres://postgres:@localhost/travis_ci_test?sslmode=disable
go:
- tip
install:
- go get .
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- make build
- make test-unit -s=mnemosyne-travis-unit
- make test-postgres -s=mnemosyne-travis-postgres
notifications:
  slack:
    secure: $SLACK_SECURE
