language: go
addons:
  postgresql: "9.3"
go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip
install:
  - go get .
script:
  - go build
  - cp conf/travis_postgres.xml conf/testing.xml
  - go init
  - go test -tags postgres
