language: go
addons:
  postgresql: '9.3'
env:
  MNEMOSYNE_HOST: localhost
  MNEMOSYNE_PORT: 9001
  MNEMOSYNE_SUBSYSTEM: mnemosyne_travis
  MNEMOSYNE_LOGGER_FORMAT: humane
  MNEMOSYNE_LOGGER_ADAPTER: stdout
  MNEMOSYNE_LOGGER_LEVEL: 6
  MNEMOSYNE_MONITORING_ENGINE: prometheus
  MNEMOSYNE_STORAGE_ENGINE: postgres
  MNEMOSYNE_STORAGE_POSTGRES_CONNECTION_STRING: postgres://postgres:@localhost/travis_ci_test?sslmode=disable
  MNEMOSYNE_STORAGE_POSTGRES_TABLE_NAME: session
  MNEMOSYNE_STORAGE_POSTGRES_RETRY: 10
go:
- tip
install:
- go get github.com/stretchr/testify/...
- go get github.com/onsi/ginkgo
- go get github.com/onsi/gomega
- make get
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- make build
- make test-unit
- make test-postgres
notifications:
  slack:
    secure: SLACK_SECURE

