language: go
addons:
  postgresql: '9.3'
env: MNEMOSYNE_ENV=testing
go:
- 1.4
- tip
install:
- go get .
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- go build
- cp conf/travis_postgres.xml conf/testing.xml
- ./mnemosyne init
- cd test/lib && go get && go test -tags postgres
notifications:
  slack:
    secure: UorEy0vXbEfiEHaSohjuTf4zDPjnjNBMR4pN3ePGV0vyPM0S1AlXjm78RdfENRpI28IjqISgLOO6gFBj7PKUXURaM4u1dqOOPhNbiF0DIgZa+yyUrhdbxL/TKzLCtRqHUhpuFHsAyx1aKAfJnF83bjilWZYBhdjrlg8ot6mv2QPI19j8R4BbNalDfAY5XO2wz6mqCz/LXZtMONsdE5Gm3IBl2+vWJYAjXaWKxySRThEdIAkJi2/oB8EO+GlwJfjb6OLuRy9sZlHam3A4d8cVxp/g7AFSF9ctwht5A4C3u2cShMNxnqcI1eHfR5K97q26MElJASIPlqNLIpGuMhqUU/YmbIzKfeCZmuzEGyqIHbUb1xl28CTyYrN6uIsxkoN7P8N9bHaLxdJNxshn8hoZKRPo0+YoMdM+ACF3NueVQJSeT+tAhNTr6lZ8BtFNRHhBN6duC49sUDe8GWch3MvqbYcCxXcJ48jFPyXXC4oGX/9pjOT1acVr6VmK79eNOC74z68ibm1wq5pYE6U2GDviUCnISYZMPAJeBkXcWvc9ItaGZjfpLcPve68oTWJ9XwaP1VWTkVaFhCFxuuKzp9uDf8q9zdEARnh1UhhMs4oL+NIP8dvyqw66ta4tqmZKQgKrpBAr493VJIecTo5kndi5iQN0+jSla2OvTjT4p1V/6qU=
