codecov:
  branch: master
comment:
  layout: header, diff, changes, uncovered
coverage:
  ignore:
  - mnemosynerpc/mnemosyne.pb.go
  status:
    patch: false
    project:
      default:
        branches:
        - master
        target: auto