version: '3'

services:
  postgres:
    image: postgres:9.5
    container_name: postgres-9.5-mnemosyne
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mnemosyned-1:
    container_name: mnemosyned-1
    image: piotrkowalczuk/mnemosyne:latest
    ports:
      - 20010:8080
      - 20011:8081
    environment:
      MNEMOSYNED_LOG_ENVIRONMENT: development
      MNEMOSYNED_LOG_LEVEL: debug
      MNEMOSYNED_CLUSTER_LISTEN: mnemosyned-1:8080
      MNEMOSYNED_CLUSTER_SEEDS: mnemosyned-2:8080,mnemosyned-3:8080
      MNEMOSYNED_POSTGRES_SCHEMA: mnemosyne1
      MNEMOSYNED_TRACING_AGENT_ADDRESS: jaeger:6831
    depends_on:
      - postgres
      - jaeger
    volumes:
      - ./bin/mnemosyned:/usr/local/bin/mnemosyned
      - ./scripts/docker-entrypoint.sh:/docker-entrypoint.sh
    healthcheck:
      interval: 10s
  mnemosyned-2:
    container_name: mnemosyned-2
    image: piotrkowalczuk/mnemosyne:latest
    ports:
      - 20020:8080
      - 20021:8081
    environment:
      MNEMOSYNED_LOG_ENVIRONMENT: development
      MNEMOSYNED_LOG_LEVEL: debug
      MNEMOSYNED_CLUSTER_LISTEN: mnemosyned-2:8080
      MNEMOSYNED_CLUSTER_SEEDS: mnemosyned-1:8080,mnemosyned-3:8080
      MNEMOSYNED_POSTGRES_SCHEMA: mnemosyne2
      MNEMOSYNED_TRACING_AGENT_ADDRESS: jaeger:6831
    depends_on:
      - postgres
      - jaeger
    volumes:
      - ./bin/mnemosyned:/usr/local/bin/mnemosyned
      - ./scripts/docker-entrypoint.sh:/docker-entrypoint.sh
    healthcheck:
      interval: 10s
  mnemosyned-3:
    container_name: mnemosyned-3
    image: piotrkowalczuk/mnemosyne:latest
    ports:
      - 20030:8080
      - 20031:8081
    environment:
      MNEMOSYNED_LOG_ENVIRONMENT: development
      MNEMOSYNED_LOG_LEVEL: debug
      MNEMOSYNED_CLUSTER_LISTEN: mnemosyned-3:8080
      MNEMOSYNED_CLUSTER_SEEDS: mnemosyned-1:8080,mnemosyned-2:8080
      MNEMOSYNED_POSTGRES_SCHEMA: mnemosyne3
      MNEMOSYNED_TRACING_AGENT_ADDRESS: jaeger:6831
    depends_on:
      - postgres
      - jaeger
    volumes:
      - ./bin/mnemosyned:/usr/local/bin/mnemosyned
      - ./scripts/docker-entrypoint.sh:/docker-entrypoint.sh
    healthcheck:
      interval: 10s
  mnemosynestress:
    container_name: mnemosynestress
    image: piotrkowalczuk/mnemosyne:latest
    volumes:
      - ./bin/mnemosynestress:/usr/local/bin/mnemosynestress
    depends_on:
      - mnemosyned-1
      - mnemosyned-2
      - mnemosyned-3
    command: |-
      mnemosynestress -verbose
      -cluster.static
      -cluster.static.members=mnemosyned-1:8080
      -cluster.static.members=mnemosyned-2:8080
      -cluster.static.members=mnemosyned-3:8080
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
    - 16686:16686
volumes:
  postgres-data:
    external: false
  prometheus-data:
    external: false